apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    name: app
    app: tickets
spec:
  containers:
    - name: app
      image: zvxr/tickets
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
